### ISSUE TITLE
GUI launches on Mac OS, but crashes when logging is started

### ISSUE THREAD

**Issue by mike-mosher** [CharaChorder/nexus#124] opened 2023-12-26 18:39 UTC
Here are the logs from debug mode:

» ./nexus-macos -l DEBUG                                                                                                                             c59223a@WMAC5268699
2023-12-26 12:16:59,154 - Args: Namespace(log_level='DEBUG', freqlog_db_path='/Users/<username>/Library/Application Support/CharaChorder/nexus/nexus_freqlog_db.sqlite3', command=None)
2023-12-26 12:16:59,249 - Starting new HTTPS connection (1): api.github.com:443
2023-12-26 12:16:59,488 - https://api.github.com:443 "GET /repos/CharaChorder/nexus/releases/latest HTTP/1.1" 200 1662
2023-12-26 12:17:04,915 - Starting new HTTPS connection (1): api.github.com:443
2023-12-26 12:17:05,094 - https://api.github.com:443 "GET /repos/CharaChorder/nexus/releases/latest HTTP/1.1" 200 1662
2023-12-26 12:17:05,096 - Initializing freqlog
2023-12-26 12:17:05,097 - Connecting to CharaChorder device at CharaChorder One (/dev/cu.usbmodem213201)
2023-12-26 12:21:10,677 - Listing words, limit 100, sort_by WordMetadataAttr.score, reverse True, case INSENSITIVE, search 
2023-12-26 12:21:10,677 - Listing chords, limit 100, sort_by ChordMetadataAttr.score, reverse True, search 
2023-12-26 12:21:10,679 - Getting number of words
2023-12-26 12:21:10,679 - Getting number of logged chords
2023-12-26 12:21:14,070 - Initializing freqlog
2023-12-26 12:21:15,125 - Connecting to CharaChorder device at CharaChorder One (/dev/cu.usbmodem213201)
2023-12-26 12:21:15,242 - Logging set to freqlog db at /Users/<username>/Library/Application Support/CharaChorder/nexus/nexus_freqlog_db.sqlite3
2023-12-26 12:21:15,292 - Getting 788 chords from device
2023-12-26 12:21:16,439 - Starting freqlogging
2023-12-26 12:21:16,452 - new_word_threshold=5, chord_char_threshold=5, allowed_keys_in_chord={'z', 'B', 'b', 'C', 'T', 'd', 'D', 'u', '5', 'c', 'G', '3', 'x', '_', '-', 'i', 'K', 'S', 'q', 'o', 's', 'Q', 'r', 'U', 'y', 'J', 'V', 'E', 'F', 'P', 'Z', '8', '/', 'X', 'N', 'H', '\\', '2', 'A', 'R', 't', "'", 'L', '7', 'e', 'g', 'M', '6', 'v', 'Y', 'O', 'j', 'h', 'W', 'l', '0', 'a', '1', 'n', '9', 'I', 'k', '4', 'f', 'p', 'm', '~', 'w'}, modifier_keys={<Key.alt: <58>>, <Key.cmd_r: <54>>, <Key.cmd: <55>>, <Key.alt_r: <61>>, <Key.ctrl: <59>>, <Key.ctrl_r: <62>>}
[1]    60524 illegal hardware instruction  ./nexus-macos -l DEBUG

**Comment by Raymo111** [comment] 2023-12-27 04:19
Duplicate of #7.

**Closed** 2023-12-27 04:19 UTC
